#
# This is a Shiny web application. You can run the application by clicking
# the 'Run App' button above.
#
# Find out more about building applications with Shiny here:
#
#    http://shiny.rstudio.com/
#
## LIBRARIES
library(shiny)
library(leaflet)
library(tidyverse)
library(lubridate)
library(DBI)
library(shinydashboard)
### BUFFER ZONE

## Data loading
source('C:/Users/santi/Desktop/R/Projects/Car_Accidents/Data_preloading.R')

## Connection setup
con <- dbConnect(odbc::odbc(), .connection_string = "Driver={MySQL ODBC 8.0 Unicode Driver};",
                 Database  = 'uk_car_accidents_',
                 UID       = 'root',
                 PWD       = 'donald_7rump$ismyh0m3boy',
                 Port      = 3306)


### FRONT

# Define UI 
ui <- dashboardPage(
  dashboardHeader(title = 'App title'),
  dashboardSidebar(
    sidebarMenu(
      menuItem("Dashboard", tabName = "dashboard", icon = icon("dashboard")),
      menuItem("Widgets", tabName = "widgets", icon = icon("th"))
    )
  ),
  
  ## Body content
  dashboardBody(
    fluidRow(
      tabItems(
        # First tab content
        tabItem(tabName = "dashboard",
                fluidRow(
                  box(plotOutput("plot1", height = 250)),
                  
                  box(
                    title = "Controls",
                    sliderInput("slider", "Number of observations:", 1, 100, 50)
                  )
                )
        ),
        
        # Second tab content
        tabItem(tabName = "widgets",
                #h2("Widgets tab content") # if left unchecked it outputs a 3rd unnamed tab in the tabbox generated by the h2() function call. The other 2 tabs are generated by piping with tabBox()
                #%>% 
                tabBox(width = 12,height = 12,
                  title='titulo',
                  tabPanel("Tab1",
                           "Currently selected tab from first box:",
                           verbatimTextOutput("tabset1Selected")),
                  tabPanel("Map output test", leafletOutput("mymap"),
                           p(),
                           actionButton("recalc", "New points"))
                )
        )
      )
      
    )
  )
)



### BACK

# Define server logic required to draw a histogram
server <- function(input, output) {
  # The currently selected tab from the first box
  # output$tabset1Selected <- renderText({
  #   input$tabset1
  # })
  
  points <- eventReactive(input$recalc, {Sample<-sample(1:nrow(Acc),100);
    cbind(Acc$Longitude[Sample],Acc$Latitude[Sample] )
  }, ignoreNULL = FALSE)
  
  output$mymap <- renderLeaflet({
    leaflet() %>%
    addProviderTiles(providers$Stamen.TonerLite,
                       options = providerTileOptions(noWrap = TRUE)
      ) %>%
      addMarkers(data = points(),clusterOptions = markerClusterOptions())
  })  
  
  
  
  
  
  
  # output$distPlot <- renderPlot({
  #   # generate bins based on input$bins from ui.R
  #   x    <- faithful[, 2] 
  #   bins <- seq(min(x), max(x), length.out = input$bins + 1)
  #   
  #   # draw the histogram with the specified number of bins
  #   hist(x, breaks = bins, col = 'darkgray', border = 'white')
  # })
}

# Run the application 
shinyApp(ui = ui, server = server)

